/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.config.tasks.ExampleConfig;

public class App {
    public static void main(String[] args) {
        ExampleConfig exampleConfig = new ExampleConfig();
        new Example(exampleConfig).start();
    }
}
